'use client';
import {useState} from 'react';
const W=[{n:"Billy's Creek",t:8500,v:6300,p:700,s:'At Risk'},{n:"Manuel's Branch",t:5200,v:3692,p:925,s:'Watch'},{n:'Downtown Basin',t:4700,v:3992,p:500,s:'On Track'}];
const P=[{id:'BMAP-027',n:"Billy's Creek Nutrient Reduction",w:"Billy's Creek",s:'Construction',c:4200000,e:8750,v:6900},{id:'BMAP-031',n:'Street Sweeping Expansion',w:'Citywide',s:'Monitoring',c:600000,e:1850,v:1200},{id:'BMAP-034',n:"Manuel's Branch Pond Retrofit",w:"Manuel's Branch",s:'Design',c:1800000,e:2900,v:0},{id:'BMAP-039',n:'Downtown Green Infrastructure',w:'Downtown Basin',s:'Planning',c:2100000,e:2300,v:0}];
const C=[
{id:'NC-2027-0042',project:'BMAP-027',name:"Billy's Creek Nutrient Reduction",nutrient:'TN',calc:2480,submitted:2480,verified:2125,status:'DEP Review',date:'Sep 18, 2026',owner:'A. Rivera'},
{id:'NC-2027-0038',project:'BMAP-031',name:'Street Sweeping Expansion',nutrient:'TN',calc:1200,submitted:1200,verified:1200,status:'Active',date:'Aug 30, 2026',owner:'M. Chen'},
{id:'NC-2027-0046',project:'BMAP-034',name:"Manuel's Branch Pond Retrofit",nutrient:'TN',calc:925,submitted:925,verified:0,status:'Submitted',date:'Sep 23, 2026',owner:'A. Rivera'}];
const S=[
{id:'MON-101',site:"Billy's Creek BC-04",project:'BMAP-027',date:'Sep 20, 2026',tn:1.42,tp:.18,do:5.8,turb:8.2,qa:'Validated'},
{id:'MON-102',site:"Billy's Creek BC-07",project:'BMAP-027',date:'Sep 20, 2026',tn:1.31,tp:.16,do:6.1,turb:7.5,qa:'Validated'},
{id:'MON-103',site:'Downtown DT-02',project:'BMAP-039',date:'Sep 22, 2026',tn:1.08,tp:.13,do:6.4,turb:6.9,qa:'Pending QA'}];
const E=[
{id:'EV-027-01',project:'BMAP-027',type:'Engineering Calculation',name:'Nutrient Reduction Calculation v3',status:'Approved',date:'Sep 12, 2026'},
{id:'EV-027-02',project:'BMAP-027',type:'Design',name:'90% Project Design Package',status:'Approved',date:'Aug 28, 2026'},
{id:'EV-027-03',project:'BMAP-027',type:'Monitoring',name:'September Monitoring Dataset',status:'Available',date:'Sep 21, 2026'},
{id:'EV-027-04',project:'BMAP-027',type:'DEP Correspondence',name:'Credit Review Correspondence',status:'Missing',date:'—'}];
const nf=n=>n.toLocaleString(), money=n=>'$'+(n/1e6).toFixed(1)+'M';
function Head({t,s}){return <div className="top"><div><h1>{t}</h1><p>{s}</p></div><div className="user"><div className="avatar">JD</div><div><b>John Doe</b><div className="muted">Water Quality Manager</div></div></div></div>}
function K({n,l,m}){return <div className="card"><div className="num">{n}</div><div className="label">{l}</div>{m&&<div className="muted">{m}</div>}</div>}
function Dash({go}){return <><Head t="BMAP Command Center" s="City of Fort Myers · Caloosahatchee River & Estuary"/><div className="grid4"><K n="76%" l="Milestone Achieved" m="Verified reduction"/><K n="4,416" l="lbs/yr Remaining" m="Confirmed TN gap"/><K n="2,125" l="lbs/yr Pending" m="Pending verification"/><K n="$18.7M" l="Projects in Pipeline" m="Capital portfolio"/></div><div className="two"><div className="card"><h2>2027 BMAP Milestone</h2><b>13,984 / 18,400 lbs/yr Total Nitrogen</b><div className="progress"><div className="bar" style={{width:'76%'}}/></div><div className="muted">Projected including pending credits: 87.5%</div><button className="btn" onClick={()=>go('obligations')} style={{marginTop:15}}>View Obligations</button></div><div className="card"><h2>Attention Required</h2><div className="alert risk"><b>2027 milestone at risk</b></div><div className="alert">3 credits pending verification</div><div className="alert">Monitoring evidence incomplete</div></div></div><div className="card section"><h2>Progress by Watershed</h2><table><tbody>{W.map(w=><tr key={w.n}><td><b>{w.n}</b></td><td>{nf(w.t)} target</td><td>{nf(w.v)} verified</td><td>{Math.round(w.v/w.t*100)}%</td><td><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span></td></tr>)}</tbody></table></div></>}
function Waters(){return <><Head t="Watersheds" s="Geographic view of BMAP obligations and project performance"/><div className="grid3">{W.map(w=><div className="card" key={w.n}><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span><h2>{w.n}</h2><div className="num">{Math.round(w.v/w.t*100)}%</div><div className="progress"><div className="bar" style={{width:(w.v/w.t*100)+'%'}}/></div><div className="muted">{nf(w.t-w.v)} lbs/yr remaining</div></div>)}</div></>}
function Oblig(){return <><Head t="BMAP Obligations" s="Regulatory targets, milestones and confirmed reduction position"/><div className="grid4"><K n="18,400" l="Required TN"/><K n="13,984" l="Verified"/><K n="2,125" l="Pending"/><K n="4,416" l="Confirmed Gap"/></div><div className="card"><h2>Milestone Ledger</h2><table><thead><tr><th>Milestone</th><th>Parameter</th><th>Required</th><th>Verified</th><th>Pending</th><th>Gap</th><th>Forecast</th></tr></thead><tbody><tr><td>2027</td><td>Total Nitrogen</td><td>18,400</td><td>13,984</td><td>2,125</td><td>4,416</td><td><span className="tag red">At Risk</span></td></tr><tr><td>2032</td><td>Total Nitrogen</td><td>24,800</td><td>13,984</td><td>6,400 projected</td><td>10,816</td><td><span className="tag amber">Planning</span></td></tr></tbody></table></div></>}
function Projects(){return <><Head t="Water Quality Projects" s="BMAP project portfolio, nutrient performance and capital investment"/><div className="card section"><table><thead><tr><th>Project</th><th>Watershed</th><th>Status</th><th>Capital Cost</th><th>Est. TN</th><th>Verified TN</th></tr></thead><tbody>{P.map(p=><tr key={p.id}><td><b>{p.id}</b><br/>{p.n}</td><td>{p.w}</td><td><span className="tag">{p.s}</span></td><td>{money(p.c)}</td><td>{nf(p.e)}</td><td>{nf(p.v)}</td></tr>)}</tbody></table></div></>}
function Credits(){
 const[sel,setSel]=useState(null); const c=sel?C.find(x=>x.id===sel):null;
 if(c)return <><Head t={c.id} s={`${c.name} · ${c.nutrient} credit record`}/><button className="back" onClick={()=>setSel(null)}>← Nutrient Credit Ledger</button><div className="grid4"><K n={nf(c.calc)} l="Calculated" m="lbs/yr"/><K n={nf(c.submitted)} l="Submitted" m="lbs/yr"/><K n={c.verified?nf(c.verified):'—'} l="Verified" m="lbs/yr"/><K n={c.verified?nf(c.submitted-c.verified):'Pending'} l="Adjustment" m={c.verified?'lbs/yr difference':'Awaiting review'}/></div><div className="two"><div className="card"><h2>Credit Lifecycle</h2><div className="timeline">{['Calculated','Estimated','Submitted','DEP Review','Verified','Active'].map((x,i)=>{let idx=['Calculated','Estimated','Submitted','DEP Review','Verified','Active'].indexOf(c.status);return <span key={x} className={'step '+(i<idx?'done':i===idx?'current':'')}>{x}</span>})}</div><div className="metricline"><b>Project</b><span>{c.project}</span></div><div className="metricline"><b>Owner</b><span>{c.owner}</span></div><div className="metricline"><b>Last action</b><span>{c.date}</span></div><div className="metricline"><b>Status</b><span className="tag purple">{c.status}</span></div></div><div className="card"><h2>Supporting Evidence</h2>{E.filter(e=>e.project===c.project).map(e=><div className="evidence" key={e.id}><div><b>{e.type}</b><div className="muted">{e.name}</div></div><span className={'tag '+(e.status==='Missing'?'red':'green')}>{e.status}</span></div>)}</div></div><div className="note section">Demonstration record. Values shown in this prototype are representative workflow data, not official DEP credit determinations.</div></>
 return <><Head t="Nutrient Credit Ledger" s="Trace calculated reductions through submission, verification and active regulatory credit"/><div className="grid4"><K n="3" l="Credits Tracked"/><K n="4,605" l="lbs/yr Submitted"/><K n="3,325" l="lbs/yr Verified"/><K n="1,280" l="lbs/yr Under Review"/></div><div className="card"><table><thead><tr><th>Credit</th><th>Project</th><th>Nutrient</th><th>Calculated</th><th>Submitted</th><th>Verified</th><th>Status</th></tr></thead><tbody>{C.map(c=><tr className="click" key={c.id} onClick={()=>setSel(c.id)}><td><b>{c.id}</b></td><td>{c.project}<br/><span className="muted">{c.name}</span></td><td>{c.nutrient}</td><td>{nf(c.calc)}</td><td>{nf(c.submitted)}</td><td>{c.verified?nf(c.verified):'—'}</td><td><span className={'tag '+(c.status==='Active'?'green':c.status==='Submitted'?'amber':'purple')}>{c.status}</span></td></tr>)}</tbody></table></div></>
}
function Monitoring(){
 const[tab,setTab]=useState('monitoring');
 return <><Head t="Monitoring & Evidence" s="Water-quality observations and regulatory evidence linked to projects and credits"/><div style={{display:'flex',gap:8,margin:'20px 0'}}><button className={'btn '+(tab!=='monitoring'?'secondary':'')} onClick={()=>setTab('monitoring')}>Monitoring Data</button><button className={'btn '+(tab!=='evidence'?'secondary':'')} onClick={()=>setTab('evidence')}>Evidence Vault</button></div>{tab==='monitoring'?<><div className="grid4"><K n="3" l="Recent Samples"/><K n="2" l="Validated"/><K n="1" l="Pending QA"/><K n="2" l="Active Sites"/></div><div className="two"><div className="card"><h2>Recent Monitoring Results</h2><table><thead><tr><th>Site</th><th>Date</th><th>TN</th><th>TP</th><th>DO</th><th>QA</th></tr></thead><tbody>{S.map(s=><tr key={s.id}><td><b>{s.site}</b><div className="muted">{s.project}</div></td><td>{s.date}</td><td>{s.tn}</td><td>{s.tp}</td><td>{s.do}</td><td><span className={'tag '+(s.qa==='Validated'?'green':'amber')}>{s.qa}</span></td></tr>)}</tbody></table><div className="note" style={{marginTop:12}}>Units are demonstration values for workflow testing. Production schemas will store units, laboratory/source, method and QA metadata explicitly.</div></div><div className="card"><h2>Monitoring Locations</h2><div className="map"><div className="river"/><i className="pin" style={{left:'32%',top:'34%'}}/><i className="pin" style={{left:'60%',top:'58%'}}/></div></div></div></>:<><div className="grid4"><K n="4" l="BMAP-027 Evidence Items"/><K n="3" l="Available / Approved"/><K n="1" l="Missing"/><K n="75%" l="Evidence Readiness"/></div><div className="card"><h2>Evidence Vault</h2><table><thead><tr><th>Evidence ID</th><th>Project</th><th>Type</th><th>Document / Dataset</th><th>Date</th><th>Status</th></tr></thead><tbody>{E.map(e=><tr key={e.id}><td><b>{e.id}</b></td><td>{e.project}</td><td>{e.type}</td><td>{e.name}</td><td>{e.date}</td><td><span className={'tag '+(e.status==='Missing'?'red':'green')}>{e.status}</span></td></tr>)}</tbody></table></div></>}</>
}
function Placeholder({n,p}){return <><Head t={n} s={`Development Phase ${p}`}/><div className="card placeholder section"><h2>{n}</h2><p>This locked module will be activated in Phase {p}.</p></div></>}
export default function Home(){const[v,setV]=useState('dashboard');const nav=[['dashboard','▣ Command Center'],['watersheds','⌖ Watersheds'],['obligations','◎ BMAP Obligations'],['projects','▤ Projects'],['credits','◉ Nutrient Credits'],['monitoring','⌁ Monitoring & Evidence'],['capital','◆ Capital Planning'],['reports','▧ Reports']];let c=v==='dashboard'?<Dash go={setV}/>:v==='watersheds'?<Waters/>:v==='obligations'?<Oblig/>:v==='projects'?<Projects/>:v==='credits'?<Credits/>:v==='monitoring'?<Monitoring/>:v==='capital'?<Placeholder n="Capital Planning" p="3"/>:<Placeholder n="Reports & DEP Readiness" p="4"/>;return <div className="app"><aside className="side"><div className="brand">CivicOps</div><div className="sub">WATER QUALITY INTELLIGENCE</div><div className="nav">{nav.map(x=><button key={x[0]} className={v===x[0]?'active':''} onClick={()=>setV(x[0])}>{x[1]}</button>)}</div><div className="demo">Fort Myers Demonstration Environment<br/>Independent product demonstration.<br/>Not an official City system.</div></aside><main className="main">{c}</main></div>}
