'use client';
import {useEffect,useState} from 'react';
const W=[{n:"Billy's Creek",t:8500,v:6300,p:700,s:'At Risk'},{n:"Manuel's Branch",t:5200,v:3692,p:925,s:'Watch'},{n:'Downtown Basin',t:4700,v:3992,p:500,s:'On Track'}];
const P=[{id:'BMAP-027',n:"Billy's Creek Nutrient Reduction",w:"Billy's Creek",s:'Construction',c:4200000,e:8750,v:6900},{id:'BMAP-031',n:'Street Sweeping Expansion',w:'Citywide',s:'Monitoring',c:600000,e:1850,v:1200},{id:'BMAP-034',n:"Manuel's Branch Pond Retrofit",w:"Manuel's Branch",s:'Design',c:1800000,e:2900,v:0},{id:'BMAP-039',n:'Downtown Green Infrastructure',w:'Downtown Basin',s:'Planning',c:2100000,e:2300,v:0}];
const C=[{id:'NC-2027-0042',p:'BMAP-027',calc:2480,sub:2480,ver:2125,s:'DEP Review'},{id:'NC-2027-0038',p:'BMAP-031',calc:1200,sub:1200,ver:1200,s:'Active'},{id:'NC-2027-0046',p:'BMAP-034',calc:925,sub:925,ver:0,s:'Submitted'}];
const S=[{site:"Billy's Creek BC-04",date:'Sep 20, 2026',tn:1.42,tp:.18,do:5.8,qa:'Validated'},{site:"Billy's Creek BC-07",date:'Sep 20, 2026',tn:1.31,tp:.16,do:6.1,qa:'Validated'},{site:'Downtown DT-02',date:'Sep 22, 2026',tn:1.08,tp:.13,do:6.4,qa:'Pending QA'}];
const CAP=[
{id:'CP-101',name:"Manuel's Branch Pond Retrofit",type:'Pond Retrofit',cost:1800000,tn:925,ready:'Design',risk:'Low'},
{id:'CP-102',name:'Downtown Green Infrastructure Phase II',type:'Green Infrastructure',cost:2100000,tn:1150,ready:'Planning',risk:'Medium'},
{id:'CP-103',name:'Street Sweeping Service Expansion',type:'Operational BMP',cost:750000,tn:820,ready:'Ready',risk:'Low'},
{id:'CP-104',name:"Billy's Creek Treatment Train",type:'Treatment Train',cost:3400000,tn:1650,ready:'Concept',risk:'Medium'},
{id:'CP-105',name:'Septic-to-Sewer Priority Area',type:'Wastewater',cost:5900000,tn:2100,ready:'Feasibility',risk:'High'}
];
const nf=n=>n.toLocaleString(), money=n=>'$'+(n/1e6).toFixed(2).replace(/0$/,'').replace(/\.0$/,'')+'M';
function Head({t,s}){return <div className="top"><div><h1>{t}</h1><p>{s}</p></div><div className="user"><div className="avatar">JD</div><div><b>John Doe</b><div className="muted">Water Quality Manager</div></div></div></div>}
function K({n,l,m}){return <div className="card"><div className="num">{n}</div><div className="label">{l}</div>{m&&<div className="muted">{m}</div>}</div>}
function Dash({go}){return <><Head t="BMAP Command Center" s="City of Fort Myers · Caloosahatchee River & Estuary"/><div className="grid4"><K n="76%" l="Milestone Achieved" m="Verified reduction"/><K n="4,416" l="lbs/yr Remaining" m="Confirmed TN gap"/><K n="2,125" l="lbs/yr Pending" m="Pending verification"/><K n="$18.7M" l="Projects in Pipeline" m="Capital portfolio"/></div><div className="two"><div className="card"><h2>2027 BMAP Milestone</h2><b>13,984 / 18,400 lbs/yr Total Nitrogen</b><div className="progress"><div className="bar" style={{width:'76%'}}/></div><p className="muted">Projected including pending credits: 87.5%</p><button className="btn" onClick={()=>go('capital')}>Model Capital Plan</button></div><div className="card"><h2>Attention Required</h2><div className="alert risk"><b>4,416 lbs/yr confirmed gap remains</b></div><div className="alert">Capital scenario can close the remaining gap</div></div></div></>}
function GeoMap({mode='watershed'}){
 const items=mode==='monitoring'?
 [{x:31,y:35,t:"BC-04",d:"Billy's Creek · Validated"},{x:57,y:57,t:"BC-07",d:"Billy's Creek · Validated"},{x:75,y:31,t:"DT-02",d:"Downtown · Pending QA"}]:
 [{x:27,y:38,t:"Billy's Creek",d:"At Risk · 74% verified"},{x:51,y:58,t:"Manuel's Branch",d:"Watch · 71% verified"},{x:72,y:35,t:"Downtown Basin",d:"On Track · 85% verified"}];
 const [active,setActive]=useState(null);
 return <div className="realmap">
   <div className="mapwater water1"/><div className="mapwater water2"/>
   <div className="road r1"/><div className="road r2"/><div className="road r3"/>
   <span className="maplabel l1">Caloosahatchee River</span><span className="maplabel l2">Fort Myers</span>
   {items.map((m,i)=><button key={m.t} className={'mappin '+(active===i?'sel':'')} style={{left:m.x+'%',top:m.y+'%'}} onClick={()=>setActive(i)} title={m.t}><span>{i+1}</span></button>)}
   {active!==null&&<div className="mapcallout"><b>{items[active].t}</b><div>{items[active].d}</div></div>}
   <div className="legend"><b>{mode==='monitoring'?'Monitoring stations':'Watershed / project geography'}</b><div>● Click a numbered location for details</div></div>
 </div>
}
function Waters(){
 const[sel,setSel]=useState(null);
 if(sel!==null){const w=W[sel];return <><Head t={w.n} s="Watershed intelligence · geographic and regulatory view"/><button className="back" onClick={()=>setSel(null)}>← All Watersheds</button>
 <div className="grid4"><K n={nf(w.t)} l="TN Obligation" m="lbs/year"/><K n={nf(w.v)} l="Verified Reduction" m="lbs/year"/><K n={nf(w.t-w.v)} l="Remaining" m="lbs/year"/><K n={nf(w.p)} l="Pending Credits" m="lbs/year"/></div>
 <div className="two"><div className="card"><h2>Watershed Map</h2><GeoMap mode="watershed"/></div><div className="card"><h2>Regulatory Position</h2><div className="metricline"><b>BMAP</b><span>Caloosahatchee River & Estuary</span></div><div className="metricline"><b>Status</b><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span></div><div className="metricline"><b>Verified progress</b><span>{Math.round(w.v/w.t*100)}%</span></div><div className="metricline"><b>Pending credits</b><span>{nf(w.p)} lbs/yr</span></div><div className="progress"><div className="bar" style={{width:(w.v/w.t*100)+'%'}}/></div><div className="note">Interactive demonstration geography. Locations are illustrative until authoritative City/DEP GIS layers are connected.</div></div></div></>}
 return <><Head t="Watersheds" s="Geographic view of BMAP obligations and project performance"/><div className="two section"><div className="card"><h2>Water Quality Map</h2><GeoMap mode="watershed"/></div><div className="card"><h2>Watershed Portfolio</h2>{W.map((w,i)=><div className="evidence click" key={w.n} onClick={()=>setSel(i)}><div><b>{w.n}</b><div className="muted">{nf(w.t-w.v)} lbs/yr remaining · {Math.round(w.v/w.t*100)}% verified</div></div><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span></div>)}</div></div>
 <div className="grid3">{W.map((w,i)=><div className="card" key={w.n}><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span><h2>{w.n}</h2><div className="num">{Math.round(w.v/w.t*100)}%</div><div className="progress"><div className="bar" style={{width:(w.v/w.t*100)+'%'}}/></div><button className="btn" onClick={()=>setSel(i)}>Open Watershed</button></div>)}</div></>
}
function Oblig(){return <><Head t="BMAP Obligations" s="Regulatory targets, milestones and confirmed reduction position"/><div className="grid4"><K n="18,400" l="Required TN"/><K n="13,984" l="Verified"/><K n="2,125" l="Pending"/><K n="4,416" l="Confirmed Gap"/></div><div className="card"><h2>Milestone Ledger</h2><table><tbody><tr><td><b>2027</b></td><td>Total Nitrogen</td><td>18,400 required</td><td>13,984 verified</td><td>4,416 gap</td><td><span className="tag red">At Risk</span></td></tr><tr><td><b>2032</b></td><td>Total Nitrogen</td><td>24,800 required</td><td>13,984 verified</td><td>10,816 gap</td><td><span className="tag amber">Planning</span></td></tr></tbody></table></div></>}
function Projects(){return <><Head t="Water Quality Projects" s="BMAP project portfolio, nutrient performance and capital investment"/><div className="card section"><table><thead><tr><th>Project</th><th>Watershed</th><th>Status</th><th>Capital Cost</th><th>Est. TN</th><th>Verified TN</th></tr></thead><tbody>{P.map(p=><tr key={p.id}><td><b>{p.id}</b><br/>{p.n}</td><td>{p.w}</td><td><span className="tag">{p.s}</span></td><td>{money(p.c)}</td><td>{nf(p.e)}</td><td>{nf(p.v)}</td></tr>)}</tbody></table></div></>}
function Credits(){return <><Head t="Nutrient Credit Ledger" s="Trace calculated reductions through submission, verification and active regulatory credit"/><div className="grid4"><K n="3" l="Credits Tracked"/><K n="4,605" l="lbs/yr Submitted"/><K n="3,325" l="lbs/yr Verified"/><K n="1,280" l="lbs/yr Under Review"/></div><div className="card"><table><thead><tr><th>Credit</th><th>Project</th><th>Calculated</th><th>Submitted</th><th>Verified</th><th>Status</th></tr></thead><tbody>{C.map(c=><tr key={c.id}><td><b>{c.id}</b></td><td>{c.p}</td><td>{nf(c.calc)}</td><td>{nf(c.sub)}</td><td>{c.ver?nf(c.ver):'—'}</td><td><span className={'tag '+(c.s==='Active'?'green':c.s==='Submitted'?'amber':'purple')}>{c.s}</span></td></tr>)}</tbody></table></div></>}
function Monitoring(){
 const[tab,setTab]=useState('data');
 return <><Head t="Monitoring & Evidence" s="Water-quality observations and regulatory evidence linked to projects and credits"/>
 <div style={{display:'flex',gap:8,margin:'20px 0'}}><button className={'btn '+(tab!=='data'?'secondary':'')} onClick={()=>setTab('data')}>Monitoring Data</button><button className={'btn '+(tab!=='map'?'secondary':'')} onClick={()=>setTab('map')}>Monitoring Map</button><button className={'btn '+(tab!=='evidence'?'secondary':'')} onClick={()=>setTab('evidence')}>Evidence Vault</button></div>
 {tab==='data'&&<><div className="grid4"><K n="3" l="Recent Samples"/><K n="2" l="Validated"/><K n="1" l="Pending QA"/><K n="2" l="Active Sites"/></div><div className="card"><h2>Recent Monitoring Results</h2><table><thead><tr><th>Site</th><th>Date</th><th>TN</th><th>TP</th><th>DO</th><th>QA</th></tr></thead><tbody>{S.map(s=><tr key={s.site}><td><b>{s.site}</b></td><td>{s.date}</td><td>{s.tn}</td><td>{s.tp}</td><td>{s.do}</td><td><span className={'tag '+(s.qa==='Validated'?'green':'amber')}>{s.qa}</span></td></tr>)}</tbody></table></div></>}
 {tab==='map'&&<div className="two"><div className="card"><h2>Monitoring Locations</h2><GeoMap mode="monitoring"/></div><div className="card"><h2>Station Status</h2>{S.map(s=><div className="evidence" key={s.site}><div><b>{s.site}</b><div className="muted">{s.date} · TN {s.tn} · TP {s.tp}</div></div><span className={'tag '+(s.qa==='Validated'?'green':'amber')}>{s.qa}</span></div>)}</div></div>}
 {tab==='evidence'&&<><div className="grid4"><K n="4" l="BMAP-027 Evidence Items"/><K n="3" l="Available / Approved"/><K n="1" l="Missing"/><K n="75%" l="Evidence Readiness"/></div><div className="card"><h2>Evidence Vault</h2><div className="evidence"><b>Engineering Calculation</b><span className="tag green">Approved</span></div><div className="evidence"><b>90% Project Design Package</b><span className="tag green">Approved</span></div><div className="evidence"><b>September Monitoring Dataset</b><span className="tag green">Available</span></div><div className="evidence"><b>DEP Credit Review Correspondence</b><span className="tag red">Missing</span></div></div></>}</>
}
function Capital(){
 const [selected,setSelected]=useState([2,3,4]);
 const toggle=i=>setSelected(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i]);
 const picks=CAP.filter((_,i)=>selected.includes(i));
 const cost=picks.reduce((a,p)=>a+p.cost,0), tn=picks.reduce((a,p)=>a+p.tn,0), gap=4416;
 const pct=Math.min(100,Math.round(tn/gap*100)), remain=Math.max(0,gap-tn), surplus=Math.max(0,tn-gap);
 const cpl=tn?Math.round(cost/tn):0;
 const ranked=[...CAP].sort((a,b)=>(a.cost/a.tn)-(b.cost/b.tn));
 return <><Head t="Capital Planning" s="Model project combinations against the remaining BMAP nutrient-reduction gap"/>
 <div className="grid4"><K n="4,416" l="Confirmed TN Gap" m="lbs/year"/><K n={money(cost)} l="Scenario Cost" m={`${picks.length} projects selected`}/><K n={nf(tn)} l="Scenario Reduction" m="lbs/year"/><K n={tn?'$'+nf(cpl):'—'} l="Cost / lb TN" m="Scenario efficiency"/></div>
 <div className="two"><div className="card"><h2>Scenario Builder</h2><div className="scenarioRow head"><span></span><span>Candidate Project</span><span>Cost</span><span>TN Reduction</span><span>$/lb</span><span>Readiness</span></div>{CAP.map((p,i)=><div className="scenarioRow" key={p.id}><input type="checkbox" checked={selected.includes(i)} onChange={()=>toggle(i)}/><div><b>{p.name}</b><div className="muted">{p.id} · {p.type}</div></div><span>{money(p.cost)}</span><span>{nf(p.tn)}</span><span>${nf(Math.round(p.cost/p.tn))}</span><span className={'tag '+(p.ready==='Ready'?'green':p.risk==='High'?'red':'')}>{p.ready}</span></div>)}</div>
 <div className="card"><h2>Milestone Forecast</h2><div className="forecast">{pct}%</div><div className="muted">of confirmed 4,416 lbs/yr gap addressed</div><div className="meter" style={{margin:'16px 0'}}><div style={{width:pct+'%'}}/></div>{remain===0?<div className="goodbox"><b>✓ Scenario closes confirmed gap</b><div className="small">{surplus?nf(surplus)+' lbs/yr modeled surplus':'Target exactly met'}</div></div>:<div className="badbox"><b>{nf(remain)} lbs/yr still unresolved</b><div className="small">Add or modify candidate projects.</div></div>}<div className="metricline"><b>Current verified</b><span>13,984 lbs/yr</span></div><div className="metricline"><b>Scenario reduction</b><span>+ {nf(tn)} lbs/yr</span></div><div className="metricline"><b>Modeled total</b><span>{nf(13984+tn)} lbs/yr</span></div><div className="metricline"><b>2027 requirement</b><span>18,400 lbs/yr</span></div></div></div>
 <div className="two section"><div className="card"><h2>Project Efficiency Ranking</h2>{ranked.map((p,i)=><div className="evidence" key={p.id}><div style={{display:'flex',gap:10,alignItems:'center'}}><div className="rank">{i+1}</div><div><b>{p.name}</b><div className="muted">{nf(p.tn)} lbs/yr · {money(p.cost)}</div></div></div><b>${nf(Math.round(p.cost/p.tn))}/lb</b></div>)}</div><div className="card"><h2>Decision Summary</h2><p><b>Selected portfolio:</b> {picks.length} projects</p><p><b>Modeled investment:</b> {money(cost)}</p><p><b>Modeled TN reduction:</b> {nf(tn)} lbs/yr</p><p><b>Remaining confirmed gap:</b> {nf(remain)} lbs/yr</p><p><b>Average efficiency:</b> {tn?'$'+nf(cpl)+'/lb':'—'}</p><div className="note">Scenario results are planning estimates using demonstration data. They are not official City budgets, engineering estimates, BMAP commitments, or DEP-approved nutrient credits.</div></div></div></>
}
function Placeholder(){return <><Head t="Reports & DEP Readiness" s="Development Phase 4"/><div className="card placeholder section"><h2>Phase 4</h2><p>Executive reporting, DEP readiness packages and audit exports will be activated next.</p></div></>}

function Reports(){
 const [tab,setTab]=useState('executive');
 const [notice,setNotice]=useState('');
 const prepare=(label)=>setNotice(label+' is ready for prototype print/export.');
 return <>
  <Head t="Reports & DEP Readiness" s="Executive reporting, regulatory package readiness and audit-ready exports"/>
  <div className="grid4">
   <K n="76%" l="2027 Milestone Achieved" m="Verified position"/>
   <K n="4,416" l="Confirmed TN Gap" m="lbs/year"/>
   <K n="75%" l="BMAP-027 Evidence Ready" m="3 of 4 items available"/>
   <K n="1" l="Critical Evidence Gap" m="DEP correspondence"/>
  </div>
  {notice && <div className="success section">✓ {notice}<button className="closeNotice" onClick={()=>setNotice('')}>×</button></div>}
  <div className="reportTabs section">
   <button className={'btn '+(tab!=='executive'?'secondary':'')} onClick={()=>setTab('executive')}>Executive BMAP Report</button>
   <button className={'btn '+(tab!=='dep'?'secondary':'')} onClick={()=>setTab('dep')}>DEP Readiness Package</button>
   <button className={'btn '+(tab!=='capital'?'secondary':'')} onClick={()=>setTab('capital')}>Capital Plan Summary</button>
   <button className={'btn '+(tab!=='audit'?'secondary':'')} onClick={()=>setTab('audit')}>Audit Log</button>
  </div>

  {tab==='executive' && <div className="two">
   <div className="card reportPaper">
    <div className="reportHead"><div><div className="eyebrow">CIVICOPS · DEMONSTRATION REPORT</div><h2>2027 BMAP Executive Status</h2><div className="muted">Caloosahatchee River & Estuary · Fort Myers planning view</div></div><span className="tag red">At Risk</span></div>
    <div className="grid3 compact"><div><b>18,400</b><span>Required TN</span></div><div><b>13,984</b><span>Verified TN</span></div><div><b>4,416</b><span>Confirmed Gap</span></div></div>
    <h3>Milestone Position</h3><div className="progress"><div className="bar" style={{width:'76%'}}></div></div>
    <div className="metricline"><span>Verified achievement</span><b>76%</b></div><div className="metricline"><span>Projected including pending credits</span><b>87.5%</b></div>
    <h3>Management Attention</h3><div className="alert risk"><b>2027 milestone remains at risk.</b><div className="small">4,416 lbs/yr of confirmed TN reduction remains unresolved.</div></div>
    <div className="alert"><b>Evidence package incomplete.</b><div className="small">BMAP-027 DEP correspondence is still missing.</div></div>
    <h3>Watershed Summary</h3>{W.map(w=><div className="metricline" key={w.n}><span>{w.n}</span><span><b>{Math.round(w.v/w.t*100)}%</b> · {w.s}</span></div>)}
    <div className="reportFoot">Prototype values are demonstration workflow data and are not official City or DEP determinations.</div>
   </div>
   <div className="card"><h2>Report Actions</h2><p>Prepare a management-ready snapshot of the current BMAP position.</p><button className="btn full" onClick={()=>prepare('Executive BMAP report')}>Prepare PDF / Print View</button><button className="btn outline full" onClick={()=>prepare('Executive data extract')}>Prepare Data Extract</button><h3>Included Sections</h3>{['Milestone position','Watershed performance','Project portfolio','Nutrient-credit status','Evidence gaps','Capital-planning position'].map(x=><div className="check" key={x}>✓ {x}</div>)}</div>
  </div>}

  {tab==='dep' && <div className="two">
   <div className="card"><div className="reportHead"><div><div className="eyebrow">PACKAGE · BMAP-027</div><h2>DEP Readiness Checklist</h2></div><div className="readinessRing">75%</div></div>
    <div className="evidence"><div><b>Engineering Calculation</b><div className="muted">Nutrient Reduction Calculation v3</div></div><span className="tag green">Approved</span></div>
    <div className="evidence"><div><b>Project Design</b><div className="muted">90% Project Design Package</div></div><span className="tag green">Approved</span></div>
    <div className="evidence"><div><b>Monitoring Dataset</b><div className="muted">September Monitoring Dataset</div></div><span className="tag green">Available</span></div>
    <div className="evidence"><div><b>DEP Verification Correspondence</b><div className="muted">Credit Review Correspondence</div></div><span className="tag red">Missing</span></div>
    <div className="alert risk"><b>Submission blocker:</b> DEP verification correspondence has not been attached.</div>
   </div>
   <div className="card"><h2>Package Control</h2><div className="metricline"><b>Project</b><span>BMAP-027</span></div><div className="metricline"><b>Credit</b><span>NC-2027-0042</span></div><div className="metricline"><b>Submitted TN</b><span>2,480 lbs/yr</span></div><div className="metricline"><b>Verified TN</b><span>2,125 lbs/yr</span></div><div className="metricline"><b>Readiness</b><span>75%</span></div><button className="btn full" disabled>Package Not Ready</button><p className="note">CivicOps blocks a ready state while required evidence is missing. Production package generation would compile source documents and metadata into the City's approved submission structure.</p></div>
  </div>}

  {tab==='capital' && <div className="two">
   <div className="card reportPaper"><div className="eyebrow">CAPITAL DECISION BRIEF</div><h2>Modeled 2027 Gap-Closure Portfolio</h2>
    <div className="grid3 compact"><div><b>$10.05M</b><span>Investment</span></div><div><b>4,570</b><span>TN lbs/yr</span></div><div><b>$2,199</b><span>Cost / lb</span></div></div>
    <div className="goodbox"><b>✓ Modeled portfolio closes the confirmed gap</b><div className="small">154 lbs/yr modeled surplus above the 4,416 lbs/yr demonstration gap.</div></div>
    <h3>Selected Projects</h3>{CAP.filter((_,i)=>[2,3,4].includes(i)).map(x=><div className="evidence" key={x.id}><div><b>{x.name}</b><div className="muted">{x.id} · {x.ready}</div></div><div style={{textAlign:'right'}}><b>{money(x.cost)}</b><div className="muted">{nf(x.tn)} lbs/yr</div></div></div>)}
    <div className="reportFoot">Planning scenario only. Not an adopted budget, engineering estimate, procurement decision, or DEP-approved credit position.</div>
   </div>
   <div className="card"><h2>Decision Controls</h2><div className="metricline"><b>Current verified</b><span>13,984</span></div><div className="metricline"><b>Modeled addition</b><span>+4,570</span></div><div className="metricline"><b>Modeled total</b><span>18,554</span></div><div className="metricline"><b>Requirement</b><span>18,400</span></div><button className="btn full" onClick={()=>prepare('Capital plan summary')}>Prepare Decision Brief</button></div>
  </div>}

  {tab==='audit' && <div className="card"><div className="reportHead"><div><h2>Audit & Activity Log</h2><p className="muted">Traceability across credits, evidence, monitoring and planning decisions.</p></div><button className="btn" onClick={()=>prepare('Audit log export')}>Prepare Export</button></div>
   <table><thead><tr><th>Date</th><th>User</th><th>Record</th><th>Action</th><th>Result</th></tr></thead><tbody>
    <tr><td>Sep 22, 2026</td><td>J. Doe</td><td>DT-02</td><td>Monitoring sample entered</td><td><span className="tag amber">Pending QA</span></td></tr>
    <tr><td>Sep 21, 2026</td><td>A. Rivera</td><td>EV-027-03</td><td>Monitoring dataset attached</td><td><span className="tag green">Available</span></td></tr>
    <tr><td>Sep 18, 2026</td><td>A. Rivera</td><td>NC-2027-0042</td><td>Credit submitted for review</td><td><span className="tag purple">DEP Review</span></td></tr>
    <tr><td>Sep 12, 2026</td><td>Engineering</td><td>EV-027-01</td><td>Calculation approved</td><td><span className="tag green">Approved</span></td></tr>
   </tbody></table><div className="note section">Demonstration activity log. Production audit history would be immutable, timestamped, permission-aware and tied to authenticated users.</div>
  </div>}
 </>;
}

function PilotWorkspace(){
 const seedProjects=[...P];
 const seedSamples=[...S];
 const [role,setRole]=useState('Water Quality Manager');
 const [projects,setProjects]=useState(seedProjects);
 const [samples,setSamples]=useState(seedSamples);
 const [docs,setDocs]=useState([{name:'Nutrient Reduction Calculation v3.pdf',type:'Engineering Calculation',project:'BMAP-027',status:'Approved'},{name:'September Monitoring Dataset.csv',type:'Monitoring',project:'BMAP-027',status:'Available'}]);
 const [tab,setTab]=useState('projects');
 const [saved,setSaved]=useState(false);
 useEffect(()=>{try{let x=localStorage.getItem('civicops_phase5');if(x){x=JSON.parse(x);setProjects(x.projects||seedProjects);setSamples(x.samples||seedSamples);setDocs(x.docs||[]);setRole(x.role||'Water Quality Manager')}}catch(e){}},[]);
 useEffect(()=>{try{localStorage.setItem('civicops_phase5',JSON.stringify({projects,samples,docs,role}));setSaved(true);let t=setTimeout(()=>setSaved(false),900);return()=>clearTimeout(t)}catch(e){}},[projects,samples,docs,role]);
 const addProject=e=>{e.preventDefault();let f=new FormData(e.currentTarget);let id=f.get('id').trim();if(!id)return;setProjects(x=>[...x,{id,n:f.get('name'),w:f.get('watershed'),s:f.get('status'),c:Number(f.get('cost')||0),e:Number(f.get('tn')||0),v:0}]);e.currentTarget.reset()};
 const addSample=e=>{e.preventDefault();let f=new FormData(e.currentTarget);setSamples(x=>[{site:f.get('site'),date:f.get('date'),tn:Number(f.get('tn')),tp:Number(f.get('tp')),do:Number(f.get('do')),qa:'Pending QA'},...x]);e.currentTarget.reset()};
 const addDoc=e=>{let file=e.target.files&&e.target.files[0];if(file)setDocs(x=>[{name:file.name,type:'Uploaded Evidence',project:'BMAP-027',status:'Available'},...x]);e.target.value=''};
 const csv=(name,rows)=>{let keys=Object.keys(rows[0]||{}),body=[keys.join(','),...rows.map(r=>keys.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 const reset=()=>{if(confirm('Reset this browser workspace to the Phase 5 demonstration data?')){setProjects(seedProjects);setSamples(seedSamples);setDocs([])}};
 return <><Head t="Phase 5 · Pilot Workspace" s="Persistent pilot data, controlled entry, evidence intake and role-aware operations"/>
 <div className="foundationBanner"><div><b>Pilot Foundation Active</b><span>Changes persist in this browser across refreshes.</span></div><div className="persist">{saved?'● Saved':'● Persistent'}</div></div>
 <div className="grid4"><K n={projects.length} l="Project Records" m="Editable pilot dataset"/><K n={samples.length} l="Monitoring Samples" m="Controlled data entry"/><K n={docs.length} l="Evidence Files" m="Document intake"/><K n="4" l="Role Profiles" m="Access model prototype"/></div>
 <div className="two"><div className="card"><h2>Session & Access Control</h2><label className="field"><span>Active role</span><select value={role} onChange={e=>setRole(e.target.value)}><option>Water Quality Manager</option><option>Project Manager</option><option>Field / Monitoring Staff</option><option>Read-Only Executive</option></select></label><div className="permissionGrid"><div>View portfolio <b>✓</b></div><div>Edit records <b>{role==='Read-Only Executive'?'—':'✓'}</b></div><div>Upload evidence <b>{role==='Read-Only Executive'?'—':'✓'}</b></div><div>Approve / submit <b>{role==='Water Quality Manager'?'✓':'—'}</b></div></div></div><div className="card"><h2>Production Connection Status</h2><div className="statusrow"><span>Browser persistence</span><span className="tag green">Active</span></div><div className="statusrow"><span>Authenticated City identity</span><span className="tag amber">Integration Required</span></div><div className="statusrow"><span>Managed database</span><span className="tag amber">Integration Required</span></div><div className="statusrow"><span>Authoritative GIS</span><span className="tag amber">Integration Required</span></div><div className="statusrow"><span>Secure document storage</span><span className="tag amber">Integration Required</span></div></div></div>
 <div className="reportTabs section"><button className={'btn '+(tab!=='projects'?'secondary':'')} onClick={()=>setTab('projects')}>Project Records</button><button className={'btn '+(tab!=='samples'?'secondary':'')} onClick={()=>setTab('samples')}>Monitoring Entry</button><button className={'btn '+(tab!=='evidence'?'secondary':'')} onClick={()=>setTab('evidence')}>Evidence Intake</button><button className={'btn '+(tab!=='architecture'?'secondary':'')} onClick={()=>setTab('architecture')}>Production Architecture</button></div>
 {tab==='projects'&&<div className="two"><div className="card"><div className="reportHead"><div><h2>Persistent Project Register</h2><p className="muted">New records remain after browser refresh.</p></div><button className="btn outline" onClick={()=>csv('civicops-projects.csv',projects)}>Export CSV</button></div><table><thead><tr><th>ID</th><th>Project</th><th>Status</th><th>Est. TN</th><th></th></tr></thead><tbody>{projects.map((x,i)=><tr key={x.id+i}><td><b>{x.id}</b></td><td>{x.n}<div className="muted">{x.w}</div></td><td><span className="tag">{x.s}</span></td><td>{nf(x.e)}</td><td>{role!=='Read-Only Executive'&&<button className="miniDanger" onClick={()=>setProjects(p=>p.filter((_,j)=>j!==i))}>Remove</button>}</td></tr>)}</tbody></table></div><div className="card"><h2>Create Project</h2>{role==='Read-Only Executive'?<div className="note">This role has view-only access.</div>:<form className="formgrid" onSubmit={addProject}><label className="field"><span>Project ID</span><input name="id" placeholder="BMAP-040" required/></label><label className="field"><span>Project name</span><input name="name" placeholder="Project name" required/></label><label className="field"><span>Watershed</span><select name="watershed"><option>Billy's Creek</option><option>Manuel's Branch</option><option>Downtown Basin</option><option>Citywide</option></select></label><label className="field"><span>Status</span><select name="status"><option>Planning</option><option>Design</option><option>Construction</option><option>Monitoring</option></select></label><label className="field"><span>Capital cost ($)</span><input name="cost" type="number" min="0"/></label><label className="field"><span>Estimated TN lbs/yr</span><input name="tn" type="number" min="0" required/></label><button className="btn full" type="submit">Create Project Record</button></form>}</div></div>}
 {tab==='samples'&&<div className="two"><div className="card"><div className="reportHead"><div><h2>Monitoring Records</h2><p className="muted">New entries default to Pending QA.</p></div><button className="btn outline" onClick={()=>csv('civicops-monitoring.csv',samples)}>Export CSV</button></div><table><thead><tr><th>Site</th><th>Date</th><th>TN</th><th>TP</th><th>DO</th><th>QA</th></tr></thead><tbody>{samples.map((x,i)=><tr key={x.site+i}><td><b>{x.site}</b></td><td>{x.date}</td><td>{x.tn}</td><td>{x.tp}</td><td>{x.do}</td><td><span className={'tag '+(x.qa==='Validated'?'green':'amber')}>{x.qa}</span></td></tr>)}</tbody></table></div><div className="card"><h2>Enter Monitoring Sample</h2>{role==='Read-Only Executive'?<div className="note">This role has view-only access.</div>:<form className="formgrid" onSubmit={addSample}><label className="field"><span>Monitoring site</span><input name="site" placeholder="BC-09" required/></label><label className="field"><span>Sample date</span><input name="date" type="date" required/></label><label className="field"><span>TN</span><input name="tn" type="number" step="0.01" required/></label><label className="field"><span>TP</span><input name="tp" type="number" step="0.01" required/></label><label className="field"><span>DO</span><input name="do" type="number" step="0.1" required/></label><button className="btn full">Save Sample for QA</button></form>}</div></div>}
 {tab==='evidence'&&<div className="two"><div className="card"><h2>Evidence Register</h2>{docs.length?docs.map((d,i)=><div className="evidence" key={d.name+i}><div><b>{d.name}</b><div className="muted">{d.type} · {d.project}</div></div><span className="tag green">{d.status}</span></div>):<div className="note">No browser-session evidence metadata yet.</div>}</div><div className="card"><h2>Evidence Intake</h2><p>Select a file to add it to the pilot evidence register. Phase 5 stores file metadata only; production storage requires a secured document repository.</p>{role==='Read-Only Executive'?<div className="note">This role has view-only access.</div>:<label className="uploadBox">Choose evidence file<input type="file" onChange={addDoc}/></label>}<div className="note section">Security safeguard: this prototype does not upload document bytes to an external service.</div></div></div>}
 {tab==='architecture'&&<div className="card"><h2>Production Architecture Gate</h2><div className="architecture"><div><b>1 · Identity</b><span>City SSO / Entra ID or approved identity provider</span></div><div><b>2 · Application API</b><span>Server-side validation, permissions and workflow rules</span></div><div><b>3 · Managed Database</b><span>Projects, obligations, credits, monitoring and audit history</span></div><div><b>4 · GIS Services</b><span>Authoritative watershed, asset and monitoring layers</span></div><div><b>5 · Document Storage</b><span>Secure evidence files, metadata, retention and versioning</span></div><div><b>6 · Reporting</b><span>Server-generated PDF/CSV and regulatory package exports</span></div><div><b>7 · Audit & Security</b><span>Immutable events, least privilege, backups and logging</span></div></div><div className="note section">Phase 5 deliberately separates working pilot features from integrations that require City-approved infrastructure, credentials and security decisions.</div><button className="btn outline section" onClick={reset}>Reset Pilot Workspace</button></div>}
 </>
}
export default function Home(){const[v,setV]=useState('dashboard');const nav=[['dashboard','▣ Command Center'],['watersheds','⌖ Watersheds'],['obligations','◎ BMAP Obligations'],['projects','▤ Projects'],['credits','◉ Nutrient Credits'],['monitoring','⌁ Monitoring & Evidence'],['capital','◆ Capital Planning'],['reports','▧ Reports'],['pilot','⚙ Phase 5 Pilot']];let c=v==='dashboard'?<Dash go={setV}/>:v==='watersheds'?<Waters/>:v==='obligations'?<Oblig/>:v==='projects'?<Projects/>:v==='credits'?<Credits/>:v==='monitoring'?<Monitoring/>:v==='capital'?<Capital/>:v==='reports'?<Reports/>:<PilotWorkspace/>;return <div className="app"><aside className="side"><div className="brand">CivicOps</div><div className="sub">WATER QUALITY INTELLIGENCE</div><div className="nav">{nav.map(x=><button key={x[0]} className={v===x[0]?'active':''} onClick={()=>setV(x[0])}>{x[1]}</button>)}</div><div className="demo">Fort Myers Demonstration Environment<br/>Independent product demonstration.<br/>Not an official City system.</div></aside><main className="main">{c}</main></div>}\n