'use client';
import {useState} from 'react';
const W=[{n:"Billy's Creek",t:8500,v:6300,p:700,s:'At Risk'},{n:"Manuel's Branch",t:5200,v:3692,p:925,s:'Watch'},{n:'Downtown Basin',t:4700,v:3992,p:500,s:'On Track'}];
const P=[{id:'BMAP-027',n:"Billy's Creek Nutrient Reduction",w:"Billy's Creek",s:'Construction',c:4200000,e:8750,v:6900},{id:'BMAP-031',n:'Street Sweeping Expansion',w:'Citywide',s:'Monitoring',c:600000,e:1850,v:1200},{id:'BMAP-034',n:"Manuel's Branch Pond Retrofit",w:"Manuel's Branch",s:'Design',c:1800000,e:2900,v:0},{id:'BMAP-039',n:'Downtown Green Infrastructure',w:'Downtown Basin',s:'Planning',c:2100000,e:2300,v:0}];
const C=[{id:'NC-2027-0042',p:'BMAP-027',calc:2480,sub:2480,ver:2125,s:'DEP Review'},{id:'NC-2027-0038',p:'BMAP-031',calc:1200,sub:1200,ver:1200,s:'Active'},{id:'NC-2027-0046',p:'BMAP-034',calc:925,sub:925,ver:0,s:'Submitted'}];
const S=[{site:"Billy's Creek BC-04",date:'Sep 20, 2026',tn:1.42,tp:.18,do:5.8,qa:'Validated'},{site:"Billy's Creek BC-07",date:'Sep 20, 2026',tn:1.31,tp:.16,do:6.1,qa:'Validated'},{site:'Downtown DT-02',date:'Sep 22, 2026',tn:1.08,tp:.13,do:6.4,qa:'Pending QA'}];
const CAP=[
{id:'CP-101',name:"Manuel's Branch Pond Retrofit",type:'Pond Retrofit',cost:1800000,tn:925,ready:'Design',risk:'Low'},
{id:'CP-102',name:'Downtown Green Infrastructure Phase II',type:'Green Infrastructure',cost:2100000,tn:1150,ready:'Planning',risk:'Medium'},
{id:'CP-103',name:'Street Sweeping Service Expansion',type:'Operational BMP',cost:750000,tn:820,ready:'Ready',risk:'Low'},
{id:'CP-104',name:"Billy's Creek Treatment Train",type:'Treatment Train',cost:3400000,tn:1650,ready:'Concept',risk:'Medium'},
{id:'CP-105',name:'Septic-to-Sewer Priority Area',type:'Wastewater',cost:5900000,tn:2100,ready:'Feasibility',risk:'High'}
];
const nf=n=>n.toLocaleString(), money=n=>'$'+(n/1e6).toFixed(2).replace(/0$/,'').replace(/\.0$/,'')+'M';
function Head({t,s}){return <div className="top"><div><h1>{t}</h1><p>{s}</p></div><div className="user"><div className="avatar">JD</div><div><b>John Doe</b><div className="muted">Water Quality Manager</div></div></div></div>}
function K({n,l,m}){return <div className="card"><div className="num">{n}</div><div className="label">{l}</div>{m&&<div className="muted">{m}</div>}</div>}
function Dash({go}){return <><Head t="BMAP Command Center" s="City of Fort Myers · Caloosahatchee River & Estuary"/><div className="grid4"><K n="76%" l="Milestone Achieved" m="Verified reduction"/><K n="4,416" l="lbs/yr Remaining" m="Confirmed TN gap"/><K n="2,125" l="lbs/yr Pending" m="Pending verification"/><K n="$18.7M" l="Projects in Pipeline" m="Capital portfolio"/></div><div className="two"><div className="card"><h2>2027 BMAP Milestone</h2><b>13,984 / 18,400 lbs/yr Total Nitrogen</b><div className="progress"><div className="bar" style={{width:'76%'}}/></div><p className="muted">Projected including pending credits: 87.5%</p><button className="btn" onClick={()=>go('capital')}>Model Capital Plan</button></div><div className="card"><h2>Attention Required</h2><div className="alert risk"><b>4,416 lbs/yr confirmed gap remains</b></div><div className="alert">Capital scenario can close the remaining gap</div></div></div></>}
function GeoMap({mode='watershed'}){
 const items=mode==='monitoring'?
 [{x:31,y:35,t:"BC-04",d:"Billy's Creek · Validated"},{x:57,y:57,t:"BC-07",d:"Billy's Creek · Validated"},{x:75,y:31,t:"DT-02",d:"Downtown · Pending QA"}]:
 [{x:27,y:38,t:"Billy's Creek",d:"At Risk · 74% verified"},{x:51,y:58,t:"Manuel's Branch",d:"Watch · 71% verified"},{x:72,y:35,t:"Downtown Basin",d:"On Track · 85% verified"}];
 const [active,setActive]=useState(null);
 return <div className="realmap">
   <div className="mapwater water1"/><div className="mapwater water2"/>
   <div className="road r1"/><div className="road r2"/><div className="road r3"/>
   <span className="maplabel l1">Caloosahatchee River</span><span className="maplabel l2">Fort Myers</span>
   {items.map((m,i)=><button key={m.t} className={'mappin '+(active===i?'sel':'')} style={{left:m.x+'%',top:m.y+'%'}} onClick={()=>setActive(i)} title={m.t}><span>{i+1}</span></button>)}
   {active!==null&&<div className="mapcallout"><b>{items[active].t}</b><div>{items[active].d}</div></div>}
   <div className="legend"><b>{mode==='monitoring'?'Monitoring stations':'Watershed / project geography'}</b><div>● Click a numbered location for details</div></div>
 </div>
}
function Waters(){
 const[sel,setSel]=useState(null);
 if(sel!==null){const w=W[sel];return <><Head t={w.n} s="Watershed intelligence · geographic and regulatory view"/><button className="back" onClick={()=>setSel(null)}>← All Watersheds</button>
 <div className="grid4"><K n={nf(w.t)} l="TN Obligation" m="lbs/year"/><K n={nf(w.v)} l="Verified Reduction" m="lbs/year"/><K n={nf(w.t-w.v)} l="Remaining" m="lbs/year"/><K n={nf(w.p)} l="Pending Credits" m="lbs/year"/></div>
 <div className="two"><div className="card"><h2>Watershed Map</h2><GeoMap mode="watershed"/></div><div className="card"><h2>Regulatory Position</h2><div className="metricline"><b>BMAP</b><span>Caloosahatchee River & Estuary</span></div><div className="metricline"><b>Status</b><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span></div><div className="metricline"><b>Verified progress</b><span>{Math.round(w.v/w.t*100)}%</span></div><div className="metricline"><b>Pending credits</b><span>{nf(w.p)} lbs/yr</span></div><div className="progress"><div className="bar" style={{width:(w.v/w.t*100)+'%'}}/></div><div className="note">Interactive demonstration geography. Locations are illustrative until authoritative City/DEP GIS layers are connected.</div></div></div></>}
 return <><Head t="Watersheds" s="Geographic view of BMAP obligations and project performance"/><div className="two section"><div className="card"><h2>Water Quality Map</h2><GeoMap mode="watershed"/></div><div className="card"><h2>Watershed Portfolio</h2>{W.map((w,i)=><div className="evidence click" key={w.n} onClick={()=>setSel(i)}><div><b>{w.n}</b><div className="muted">{nf(w.t-w.v)} lbs/yr remaining · {Math.round(w.v/w.t*100)}% verified</div></div><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span></div>)}</div></div>
 <div className="grid3">{W.map((w,i)=><div className="card" key={w.n}><span className={'tag '+(w.s==='On Track'?'green':w.s==='At Risk'?'red':'amber')}>{w.s}</span><h2>{w.n}</h2><div className="num">{Math.round(w.v/w.t*100)}%</div><div className="progress"><div className="bar" style={{width:(w.v/w.t*100)+'%'}}/></div><button className="btn" onClick={()=>setSel(i)}>Open Watershed</button></div>)}</div></>
}
function Oblig(){return <><Head t="BMAP Obligations" s="Regulatory targets, milestones and confirmed reduction position"/><div className="grid4"><K n="18,400" l="Required TN"/><K n="13,984" l="Verified"/><K n="2,125" l="Pending"/><K n="4,416" l="Confirmed Gap"/></div><div className="card"><h2>Milestone Ledger</h2><table><tbody><tr><td><b>2027</b></td><td>Total Nitrogen</td><td>18,400 required</td><td>13,984 verified</td><td>4,416 gap</td><td><span className="tag red">At Risk</span></td></tr><tr><td><b>2032</b></td><td>Total Nitrogen</td><td>24,800 required</td><td>13,984 verified</td><td>10,816 gap</td><td><span className="tag amber">Planning</span></td></tr></tbody></table></div></>}
function Projects(){return <><Head t="Water Quality Projects" s="BMAP project portfolio, nutrient performance and capital investment"/><div className="card section"><table><thead><tr><th>Project</th><th>Watershed</th><th>Status</th><th>Capital Cost</th><th>Est. TN</th><th>Verified TN</th></tr></thead><tbody>{P.map(p=><tr key={p.id}><td><b>{p.id}</b><br/>{p.n}</td><td>{p.w}</td><td><span className="tag">{p.s}</span></td><td>{money(p.c)}</td><td>{nf(p.e)}</td><td>{nf(p.v)}</td></tr>)}</tbody></table></div></>}
function Credits(){return <><Head t="Nutrient Credit Ledger" s="Trace calculated reductions through submission, verification and active regulatory credit"/><div className="grid4"><K n="3" l="Credits Tracked"/><K n="4,605" l="lbs/yr Submitted"/><K n="3,325" l="lbs/yr Verified"/><K n="1,280" l="lbs/yr Under Review"/></div><div className="card"><table><thead><tr><th>Credit</th><th>Project</th><th>Calculated</th><th>Submitted</th><th>Verified</th><th>Status</th></tr></thead><tbody>{C.map(c=><tr key={c.id}><td><b>{c.id}</b></td><td>{c.p}</td><td>{nf(c.calc)}</td><td>{nf(c.sub)}</td><td>{c.ver?nf(c.ver):'—'}</td><td><span className={'tag '+(c.s==='Active'?'green':c.s==='Submitted'?'amber':'purple')}>{c.s}</span></td></tr>)}</tbody></table></div></>}
function Monitoring(){
 const[tab,setTab]=useState('data');
 return <><Head t="Monitoring & Evidence" s="Water-quality observations and regulatory evidence linked to projects and credits"/>
 <div style={{display:'flex',gap:8,margin:'20px 0'}}><button className={'btn '+(tab!=='data'?'secondary':'')} onClick={()=>setTab('data')}>Monitoring Data</button><button className={'btn '+(tab!=='map'?'secondary':'')} onClick={()=>setTab('map')}>Monitoring Map</button><button className={'btn '+(tab!=='evidence'?'secondary':'')} onClick={()=>setTab('evidence')}>Evidence Vault</button></div>
 {tab==='data'&&<><div className="grid4"><K n="3" l="Recent Samples"/><K n="2" l="Validated"/><K n="1" l="Pending QA"/><K n="2" l="Active Sites"/></div><div className="card"><h2>Recent Monitoring Results</h2><table><thead><tr><th>Site</th><th>Date</th><th>TN</th><th>TP</th><th>DO</th><th>QA</th></tr></thead><tbody>{S.map(s=><tr key={s.site}><td><b>{s.site}</b></td><td>{s.date}</td><td>{s.tn}</td><td>{s.tp}</td><td>{s.do}</td><td><span className={'tag '+(s.qa==='Validated'?'green':'amber')}>{s.qa}</span></td></tr>)}</tbody></table></div></>}
 {tab==='map'&&<div className="two"><div className="card"><h2>Monitoring Locations</h2><GeoMap mode="monitoring"/></div><div className="card"><h2>Station Status</h2>{S.map(s=><div className="evidence" key={s.site}><div><b>{s.site}</b><div className="muted">{s.date} · TN {s.tn} · TP {s.tp}</div></div><span className={'tag '+(s.qa==='Validated'?'green':'amber')}>{s.qa}</span></div>)}</div></div>}
 {tab==='evidence'&&<><div className="grid4"><K n="4" l="BMAP-027 Evidence Items"/><K n="3" l="Available / Approved"/><K n="1" l="Missing"/><K n="75%" l="Evidence Readiness"/></div><div className="card"><h2>Evidence Vault</h2><div className="evidence"><b>Engineering Calculation</b><span className="tag green">Approved</span></div><div className="evidence"><b>90% Project Design Package</b><span className="tag green">Approved</span></div><div className="evidence"><b>September Monitoring Dataset</b><span className="tag green">Available</span></div><div className="evidence"><b>DEP Credit Review Correspondence</b><span className="tag red">Missing</span></div></div></>}</>
}
function Capital(){
 const [selected,setSelected]=useState([2,3,4]);
 const toggle=i=>setSelected(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i]);
 const picks=CAP.filter((_,i)=>selected.includes(i));
 const cost=picks.reduce((a,p)=>a+p.cost,0), tn=picks.reduce((a,p)=>a+p.tn,0), gap=4416;
 const pct=Math.min(100,Math.round(tn/gap*100)), remain=Math.max(0,gap-tn), surplus=Math.max(0,tn-gap);
 const cpl=tn?Math.round(cost/tn):0;
 const ranked=[...CAP].sort((a,b)=>(a.cost/a.tn)-(b.cost/b.tn));
 return <><Head t="Capital Planning" s="Model project combinations against the remaining BMAP nutrient-reduction gap"/>
 <div className="grid4"><K n="4,416" l="Confirmed TN Gap" m="lbs/year"/><K n={money(cost)} l="Scenario Cost" m={`${picks.length} projects selected`}/><K n={nf(tn)} l="Scenario Reduction" m="lbs/year"/><K n={tn?'$'+nf(cpl):'—'} l="Cost / lb TN" m="Scenario efficiency"/></div>
 <div className="two"><div className="card"><h2>Scenario Builder</h2><div className="scenarioRow head"><span></span><span>Candidate Project</span><span>Cost</span><span>TN Reduction</span><span>$/lb</span><span>Readiness</span></div>{CAP.map((p,i)=><div className="scenarioRow" key={p.id}><input type="checkbox" checked={selected.includes(i)} onChange={()=>toggle(i)}/><div><b>{p.name}</b><div className="muted">{p.id} · {p.type}</div></div><span>{money(p.cost)}</span><span>{nf(p.tn)}</span><span>${nf(Math.round(p.cost/p.tn))}</span><span className={'tag '+(p.ready==='Ready'?'green':p.risk==='High'?'red':'')}>{p.ready}</span></div>)}</div>
 <div className="card"><h2>Milestone Forecast</h2><div className="forecast">{pct}%</div><div className="muted">of confirmed 4,416 lbs/yr gap addressed</div><div className="meter" style={{margin:'16px 0'}}><div style={{width:pct+'%'}}/></div>{remain===0?<div className="goodbox"><b>✓ Scenario closes confirmed gap</b><div className="small">{surplus?nf(surplus)+' lbs/yr modeled surplus':'Target exactly met'}</div></div>:<div className="badbox"><b>{nf(remain)} lbs/yr still unresolved</b><div className="small">Add or modify candidate projects.</div></div>}<div className="metricline"><b>Current verified</b><span>13,984 lbs/yr</span></div><div className="metricline"><b>Scenario reduction</b><span>+ {nf(tn)} lbs/yr</span></div><div className="metricline"><b>Modeled total</b><span>{nf(13984+tn)} lbs/yr</span></div><div className="metricline"><b>2027 requirement</b><span>18,400 lbs/yr</span></div></div></div>
 <div className="two section"><div className="card"><h2>Project Efficiency Ranking</h2>{ranked.map((p,i)=><div className="evidence" key={p.id}><div style={{display:'flex',gap:10,alignItems:'center'}}><div className="rank">{i+1}</div><div><b>{p.name}</b><div className="muted">{nf(p.tn)} lbs/yr · {money(p.cost)}</div></div></div><b>${nf(Math.round(p.cost/p.tn))}/lb</b></div>)}</div><div className="card"><h2>Decision Summary</h2><p><b>Selected portfolio:</b> {picks.length} projects</p><p><b>Modeled investment:</b> {money(cost)}</p><p><b>Modeled TN reduction:</b> {nf(tn)} lbs/yr</p><p><b>Remaining confirmed gap:</b> {nf(remain)} lbs/yr</p><p><b>Average efficiency:</b> {tn?'$'+nf(cpl)+'/lb':'—'}</p><div className="note">Scenario results are planning estimates using demonstration data. They are not official City budgets, engineering estimates, BMAP commitments, or DEP-approved nutrient credits.</div></div></div></>
}
function Placeholder(){return <><Head t="Reports & DEP Readiness" s="Development Phase 4"/><div className="card placeholder section"><h2>Phase 4</h2><p>Executive reporting, DEP readiness packages and audit exports will be activated next.</p></div></>}
export default function Home(){const[v,setV]=useState('dashboard');const nav=[['dashboard','▣ Command Center'],['watersheds','⌖ Watersheds'],['obligations','◎ BMAP Obligations'],['projects','▤ Projects'],['credits','◉ Nutrient Credits'],['monitoring','⌁ Monitoring & Evidence'],['capital','◆ Capital Planning'],['reports','▧ Reports']];let c=v==='dashboard'?<Dash go={setV}/>:v==='watersheds'?<Waters/>:v==='obligations'?<Oblig/>:v==='projects'?<Projects/>:v==='credits'?<Credits/>:v==='monitoring'?<Monitoring/>:v==='capital'?<Capital/>:<Placeholder/>;return <div className="app"><aside className="side"><div className="brand">CivicOps</div><div className="sub">WATER QUALITY INTELLIGENCE</div><div className="nav">{nav.map(x=><button key={x[0]} className={v===x[0]?'active':''} onClick={()=>setV(x[0])}>{x[1]}</button>)}</div><div className="demo">Fort Myers Demonstration Environment<br/>Independent product demonstration.<br/>Not an official City system.</div></aside><main className="main">{c}</main></div>}
